### ISSUE TITLE
Midi out via USB

### ISSUE THREAD

**Issue by noisyneil** [tsbkelly/Streamdeck-Midibutton#11]
Hi! I have an HX Stomp guitar pedal that changes presets via Program Control changes. It's set to channel 1, as is your MIDI plugin, but nothing happens when I trigger the PC message. Perhaps I'm missing some vital step? 

Cheers and all the best!

Neil

**Comment by tsbkelly** [comment]
Hi,

Can you check the output from the Streamdeck MIDI port using MIDI Monitor or similar, please? Also, you need to change the default value of the "MIDI Program Change Number" in the settings before the PC is sent correctly.

Cheers

**Comment by noisyneil** [comment]
Hi,


Thanks for the quick reply!

I checked with Midi Monitor and it’s sending the correct PC on the correct channel. I have to assume it’s an issue with the HX Stomp.

All the best,

Neil

**Comment by tsbkelly** [comment]
Thanks for letting me know - good luck making it work.
