### ISSUE TITLE
New Midi Button Update Deletes Saved Midi Numbers

### ISSUE THREAD

**Issue by yumatripp** [tsbkelly/Streamdeck-Midibutton#3]
It seems the latest update for Midi Button on Stream Deck on Mac OS 10.15.6 causes any profile that gets imported, or exists in Stream Deck, resets all midi numbers on all buttons to 1 (and/or 0 depending on the button style).

3 of us have already confirmed that even importing a copy of a backup profile into the Stream Deck system overwrites the saved information. I can re-save a profile after i've re-entered the midi numbers onto the buttons, but I have almost 100 pages in various projects that is now lost. Jesus.

Help?

**Comment by tsbkelly** [comment]
Hi,

Sorry you're having this problem. It's not something I've experienced in my testing. I've checked with Corsair, and they think this shouldn't be happening. Could you send me your backup profile, please, and could you ask your friends/colleagues who have also experienced this problem to get in touch? Can I ask what you're using the plugin for?

Thanks

**Comment by jbreher** [comment]
I'm having the same issue. Using the plugin to send Bank Change LSB and PC. Worked the first time I used it. Second time, would not work. Many (All?) parameters are being reset to zero. Uninstall reinstall of the plugin restored the original parameter values - at least on the first action I triggered. But then they all reverted to zero.

Bear in mind this is the first time I have employed a third party plugin on Stream Deck - I may be suffering user error.

I'm on Mac 10.15.7

I'd be happy to send whatever might help, but I don't know where to look for the various assets.

**Comment by tsbkelly** [comment]
Hi Joe,

Could you send me all of the Midibutton logs, please? You'll find them in ~/Library/Logs/StreamDeck/ (if you open a Finder window and click Go > Go to Folder that'll get you there). It would also be helpful to know when your instances reverted to zero - after you'd triggered an action/after a restart etc.

Thanks

**Comment by jbreher** [comment]
Hi Tom - here's a zip of the log folder. 

Once the problem arises, the values revert to zero immediately upon selecting another action to edit. (Am I missing an explicit 'save'?).

One thing that occurred to me: I do not have a physical HW StreamDeck. I am using the elgato streamdeck app on iPhone for the buttons. Don't know if it's relevant, but it seems worth mentioning.

[StreamDeck-MidiButton-Logs-jbreher-20201206.zip](https://github.com/tsbkelly/Streamdeck-Midibutton/files/5649390/StreamDeck-MidiButton-Logs-jbreher-20201206.zip)

**Comment by tsbkelly** [comment]
Joe,

Sorry - I should have asked you to turn on the "Debug" option in the midibutton property page. Could you switch that on, please? Then if you play around with the settings etc. a bit more and send me the logs again that would be great.

Cheers

**Comment by jbreher** [comment]
Sounds logical. New zipfile attached.

New behavior: The Bank change messages seem to be retaining their settings today - Channel, CC#, and value.

PC messages are still resetting channel and value to zero upon navigating to another button and back.

[StreamDeck-MidiButton-logs-jbreher-20201206b.zip](https://github.com/tsbkelly/Streamdeck-Midibutton/files/5649555/StreamDeck-MidiButton-logs-jbreher-20201206b.zip)

**Comment by tsbkelly** [comment]
Hi both,

I've just corrected a bug, which should hopefully solve this issue. Can you try downloading the new release and installing that, please? You should then be able to restore your backup profiles correctly.

Cheers

**Comment by jbreher** [comment]
Thanks. Can you point me to instructions to updating? I've only installed Stream Deck plugins through the Stream Deck GUI. My instance thinks 1.06 of Nov 30 is the latest.

**Comment by tsbkelly** [comment]
Sure - go to https://github.com/tsbkelly/Streamdeck-Midibutton/blob/master/Release/co.uk.clarionmusic.midibutton.streamDeckPlugin - click on Download. When the file has downloaded open it from Finder. The Stream Deck application will probably warn about opening it, so click OK. You should then see that you have V1.07 installed. Let me know how you get on.

**Comment by jbreher** [comment]
Well...

It seems to now be retaining values. This is forward progress. 

However... now it appears that it is not sending CC 0x20 messages (Bank Change LSB). It is retaining their values, but clicking a button with nothing but that CC sends nothing out. Clicking a button with a multi action with: Bank Change and; PC results in only the PC sent on the wire.

**Comment by tsbkelly** [comment]
I've just uploaded another release - could you try this one to see if that fixes the problem, please?

**Comment by jbreher** [comment]
Preliminary results look good. Let me poke at it a little more and see if I can find a way to break it.
Thanks!

**Comment by jbreher** [comment]
So far, so good - with one disclaimer.

At one point, I thought it was not completely emptying your output buffer (note the implied assumption of your architecture, which may not be accurate). I thought I was seeing this intermittently. 
When occurring: From a multi-action (Bank Change;Program Change), the first message would be sent, but the program change would not. Invoking another MIDI button, either single or multi, would 'push out' the missing PC, then the messages expected for that button.

I'm pretty sure I did see this occurring. Now it's not occurring. 
Accordingly, it may be operator error on my part, or you may actually have a latent issue here.

If it pops up again, I'll let you know. 

--------
Now I need to copy my library of developed patch changes to my other profiles. Which brings a question: Is there some human-readable file that stores these configuration parameters? Might it be feasible to copy-and-paste between profiles?

**Comment by tsbkelly** [comment]
The current architecture clears the MIDI output buffer whenever you press a button (and that was incidentally the location of one of the bugs - the buffer wasn't being cleared properly), so it shouldn't be occurring like that after this update. That said, I may have missed another bug! If you could keep testing that would be great.

Unfortunately all data for each button is stored in the Streamdeck application database, and there isn't a human-readable way of accessing it. Even plugins have to request the data stored via the plugin API, rather than reading it directly

**Comment by snattack** [comment]
I have the same problem. My entire Streamdeck template has been wiped of all it's values after updating (which consists of multiple pages controlling my orchestral template), which will set me back half a day or so just fixing the buttons (in the middle of a deadline). It would have saved A LOT of time if I were able to type in the Midi CC-changes instead of using a dropdown-list, since I'm using CC102 to control various stuff it's in an awkward place. Also, it would help having the old releases (with version history) here on Git so it's possible to revert back to an earlier release.

It seems to retain the values after updating to 1.07, but I hope this never happens again.

**Comment by tsbkelly** [comment]
@snattack Unlike Joe, your comments are neither constructive, nor helpful. You haven't provided me with logs so I can check to see if the bug has been fixed. I hope it has, as it's obvious that this open-source software (which I developed in my spare time) is crucial to your workflow. You did backup all of your critical profiles, didn't you? So you can now restore them?

I'll consider making the change you have asked for re. MIDI CC, but frankly you haven't asked very nicely.

All versions of ALL files are available on Git - that's the point of Git. You can find all the releases of the plugin by browsing the repository history (available here - https://github.com/tsbkelly/Streamdeck-Midibutton/commits/master/Release).

I hope it never happens again, but I can't promise that it won't. If you're happy to pay for a brush tester then I'll employ one to ensure there are as few bugs as possible on release. I can't guarantee there won't be, though. Are there any bugs in your DAW?

**Comment by snattack** [comment]
Hello,

I’m sorry, my earlier comment came of out frustration. Also, I was not aware of the repo history function, most other software’s I’ve used from Git has a structure with ”latest” and then all version numbers in sub dirs. And I work in game development myself (as a sound designer, not a ”real” developer), so I know it’s difficult covering all scenarios and making stuff water proof.

Anyway: Restoring from backup didn’t help since it was loading the same version of the plugin. So I re-did all the buttons manually, and at least when I left the workstation yesterday, it seemed to work.

I’d be happy to make a small donation for your work, it is crucial in my workflow.

All the best.

**Comment by tsbkelly** [comment]
Thanks for the apology, and the offer. Don't worry about a donation, unless you want to give something to charity.

I had a look at your request for changing MIDI CC input - if you click on the dropdown list, you can type the required number (102, in your case) and the list should jump directly to the required number. Give that a try.

**Comment by snattack** [comment]
Thanks, it actually works, but for some reason it slightly "flimsy". Sometimes it jumps to another number (which was the reason for me bringing it up, I tried it under stress I assume), but it seems writing the number with consistent timing, and directly opening the list without scrolling in it, works.

Anyway, thanks for making this function for the Streamdeck. It has helped tremendously in my workflow.
