### ISSUE TITLE
Lost MIDI Note values in Stream Deck MIDButton

### ISSUE THREAD

**Issue by nonchai** [tsbkelly/Streamdeck-Midibutton#4]
[Uploading midibuttonlogs.zip…]()

**Comment by nonchai** [comment]
[midibuttonlogs.zip](https://github.com/tsbkelly/Streamdeck-Midibutton/files/5724711/midibuttonlogs.zip)

**Comment by tsbkelly** [comment]
Hi,

That looks like it's all behaving correctly. Can you try manually setting some of the parameters, closing the Stream Deck application, reopening and then checking that the parameters are retained?

**Comment by tsbkelly** [comment]
I don't think this is a Catalina/Big Sur issue - I rewrote the plugin to be a lot more efficient, but as part of that I had to change the internal architecture. There was a bug that I missed, and it looks like it's wiped settings in some (all?) instances. If the plugin is working as you expect now you can either recreate your settings, or you can download the previous version (you should be able to access it [here](https://github.com/tsbkelly/Streamdeck-Midibutton/blob/b980d7fba3dbe9c5bc27e8c8f357a79869a3f0ad/Release/co.uk.clarionmusic.midibutton.streamDeckPlugin) and run on the old version. I'd advise recreating, though - every time I update the plugin in the future you'll have to re-download the old version.

**Comment by nonchai** [comment]
Ok

ive quite SD and re launched and then ive re-entered a few note values into midi buttons .

Result: the values get saved and restored if i've tabbed or clicked into another field , **however** i notice that if after entering a note value I simply click onto the next button to enter a value in there - the changes do not get saved.

Dan

________________________________

**Comment by tsbkelly** [comment]
Hi Dan,

I *think* that's a Stream Deck thing, rather than a Midi Button thing. There might be a way of rewriting the PI code so that the value is saved instantly, though. Is the plugin itself behaving properly otherwise?

Cheers

**Comment by nonchai** [comment]
Can you let me know when the above bug has been fixed and then - once I have a modified  MIDI button plugin installed in SD I will begin re-entering all the MIDI note values again  as you suggest - in your latest release ( beta or not )

I'm afraid I have so many midi buttons for all my instruments and articulations that its jus quicker to enter a note number in a field and then click on  the next SD button to edit midi in that one, rather than have to tab or click onto another field in MIDI button simply to trigger some  field-changed event in the MIDI button code.

regards

Nonchai

and Merry Xmas!

**Comment by nonchai** [comment]
Isn't there some kind of SD "button focus changed" event or callback you can trap?

**Comment by nonchai** [comment]
if not this is definitely a failing/bug in the SD API that needs to be addressed by the Elgato team. 

And to me -seems quite a serious flaw.

**Comment by tsbkelly** [comment]
Try [this](https://www.dropbox.com/s/l703jsbsw7iza4u/co.uk.clarionmusic.midibutton.streamDeckPlugin?dl=0) - you can beta-test it. It's not the recommended way of changing events in the PI, but if it works for you I'll update it on the store.

**Comment by nonchai** [comment]
thanks.

where do i put the file?

( or is it a double click install type thing? )

Nonchai

________________________________

**Comment by tsbkelly** [comment]
Double-click and it should install automatically

**Comment by nonchai** [comment]
thanks

I've now installed and checked this on both my Catalina mac mini and Big Sur macbook pro and all seems good.

The bugfix appears to work.

Have a great xmas

Dan

________________________________

**Comment by tsbkelly** [comment]
Thanks for letting me know. Before you rebuild your rig could you try another test for me, please? Could you reinstall the version from the Stream Deck store (you may have to uninstall and then reinstall), adjust a bunch of values, and then reinstall (by double-clicking again) the version I've sent you? Hopefully that will confirm that this latest upgrade won't wipe your (and other peoples') settings.

Have a great Christmas.

**Comment by nonchai** [comment]
ok

but probs wont be able to do this until tomorrow or weds

nonchai

________________________________

**Comment by nonchai** [comment]
Hi,

so ive reinstalled both latest streamdeck AND uninstalled reinstalled the MIDI plugin and it seems ok.

Dan

________________________________

**Comment by tsbkelly** [comment]
Glad to hear it works. I'll push an update once the Elgato guys are back at work.

**Comment by nonchai** [comment]
Hi again,

Can you tell me which version number I'm to expect?.

 I'm getting 1.07

i'm just considering updating the Big Sur macbook here to sync all the settings.

Ive downloaded and installed latest streamdeck and made sure to delete the MIDIBUttin that comes with the SD release and downloaded your "RELEASE" github plugin and double clicked on it to re-add the plugin,

By the way thanks so much for creating this plugin and have yourself and your family a happy new year.

Dan

________________________________

**Comment by tsbkelly** [comment]
Hi Dan,

Happy new year to you and your family too. The link above (https://github.com/tsbkelly/Streamdeck-Midibutton/blob/b980d7fba3dbe9c5bc27e8c8f357a79869a3f0ad/Release/co.uk.clarionmusic.midibutton.streamDeckPlugin) should download version 1.04, and you should then be able to use the plugin as previously.

Let me know how you get on.

Cheers

**Comment by nonchai** [comment]
ah so the latest version is 1.07 ?

I'd much rather re-enter all the MIDI data again if 1.07 is a major update and refactor and the way forward.

Dan

________________________________

**Comment by tsbkelly** [comment]
Hi Dan,

I'd definitely recommend that as the way forward. The underlying framework of the plugin won't change again unless it absolutely has to, so you shouldn't have this problem again.

Cheers

**Comment by nonchai** [comment]
Hi again,

i've now re-entered all the settings and backed up - using v 1.07.

All is good but one thing I noticed was that if an existing button has a MIDI Note value that is intended to be 0 - then even though the value by default is zero ( as things were reset ) then it doesnt actually transmit the right MIDI note value (0 or C-1)  unless one changes the value to something else and then back again.

Dan

________________________________

**Comment by tsbkelly** [comment]
Hi Dan,

I'm not sure I understand - value 0 for a MIDI note is note C-2 (Yamaha/Logic notation) and C-1 (Roland notation). The actual note is always the same - it's the lowest possible MIDI note according to the MIDI specification, so the plugin is sending the correct note value, AFAIK. Or do you mean something else?

Cheers

**Comment by nonchai** [comment]
yes i might have got the wrong note name ( and in any case whether its -1 or -2 tends to depend on the unit concerned in my experience ) but the key point here is that as a number i'm talking about note number 0 - clearly what appears by default.  The lowest note possible in the MIDI spec.

And what i found is that even though it displayed 0 , when button pushed it wasnt actualy sending MIDI 0 until one forces the GUI control field to generate a "changed" event ( or callback whatever ) by changing the value to something else... say 666.... and then back to 0. And then it works fine,

I had to do this to many profiles so its worth fixing.

Dan

________________________________

**Comment by tsbkelly** [comment]
Ah, I see what you mean - OK, have fixed that. When I hear back from Elgato about the other ongoing issue and fix that I'll push an update.

Cheers
