### ISSUE TITLE
All MIDI buttons suddenly stopped working

### ISSUE THREAD

**Issue by MrSkills** [tsbkelly/Streamdeck-Midibutton#8]
All the MIDI buttons on my stream deck suddenly stopped working today. When I press any button using Midibutton, it displays a yellow triangle with an exclamation icon, and no MIDI is sent.

I have tried power cycling my computer and the stream deck, and adding new buttons to the interface. Non-MIDI buttons are not affected.

I was in the middle of editing a Stream Deck profile when it happened... one minute it was working, then I edited the button I was working on (a Multi Action button I was configuring to send out several MIDI commands in sequence), and when I went to try it, there was no MIDI... and the same for all other MIDI buttons (I have spent the last few weeks making a very large setup with hundreds of buttons spread across many profiles/folders).

Any help would be much appreciated!

**Comment by MrSkills** [comment]
I've attached the logs here in case that's helpful. If I uninstall and reinstall Midibutton, will that kill all the buttons I've already made? 

[
[Stream Deck Midibutton Logs.zip](https://github.com/tsbkelly/Streamdeck-Midibutton/files/5874465/Stream.Deck.Midibutton.Logs.zip)
](url)

Not 100% sure (wasn't looking at the clock) but I think the flurry of activity at 15.17 in midibutton1.log corresponds to around the time it happened. I do know that around the time it happened there was a notification from Logic saying the number of MIDI inputs/outputs had changed.

**Comment by MrSkills** [comment]
OK this is weird, sitting at my computer browsing the web just now (looking for solutions to this problem!) and a notification pops up on my screen - it's Logic saying the number of MIDI inputs/outputs has changed.

Having been dead for around an hour, it's all randomly started working again. 

I had just deleted the multi-action 5 minutes ago to see if it made a difference (it didn't, or at least not right away). I don't know if this is related or just a coincidence...?

**Comment by MrSkills** [comment]
Just had a look at the Console and there are 20 crash reports for Midibutton in the last couple of hours. I've attached the latest one here.

[midibutton_2021-01-26-162545-1_Richards-Mac-mini.crash.zip](https://github.com/tsbkelly/Streamdeck-Midibutton/files/5874668/midibutton_2021-01-26-162545-1_Richards-Mac-mini.crash.zip)

**Comment by tsbkelly** [comment]
Hi,

Sorry to hear you're having issues. Could you send me a list of all the MIDI devices in your system, tell me whether you're using a virtual or physical port, and switch on the Debug option in the settings, please? Could you also export the profile that's giving you trouble (open the Stream Deck editor, click the cog wheel to open settings, select the correct profile, click the small downwards-facing triangle and then click Export) and attach it here?

Thanks

**Comment by MrSkills** [comment]
Hey tsbkelly, thanks so much for looking into this!

The only MIDI device that's definitely been active today is a Doepfer LMK2+ (controller keyboard, connected by USB). I might also have been running touchOSC Bridge for my iPhone (using WiFi), but I can't remember for sure (I only load it when needed, not on startup).

I also have Keyboard Maestro and BetterTouchTool running, which I believe are both capable of MIDI triggers, although I don't consciously have them set up to do that. And of course I've been running Logic (10.6.1).

The system is macOS 10.15.7 and the Stream Deck is using a virtual port called "Stream Deck".

Thanks!

**Comment by MrSkills** [comment]
Here's the profile I was working on at the time

[MODO Bass.streamDeckProfile.zip](https://github.com/tsbkelly/Streamdeck-Midibutton/files/5875399/MODO.Bass.streamDeckProfile.zip)

**Comment by MrSkills** [comment]
Just an update to say this hasn’t happened again since… my guess is it was just a crash that happened during very heavy editing of the stream deck profile.

**Comment by tsbkelly** [comment]
Thanks for the update
