### ISSUE TITLE
Program Change only sends Note C-2

### ISSUE THREAD

**Issue by DrIgnatiusCole** [tsbkelly/Streamdeck-Midibutton#9]
Very excited to be able to use my stream deck for articulation switching.

Unfortunately program changes are only sending midi note c-2.

![Screenshot 2021-02-18 at 15 05 32](https://user-images.githubusercontent.com/65957201/108376343-d38e1980-71fa-11eb-992c-cc73a4320235.png)
![Screenshot 2021-02-18 at 15 06 35](https://user-images.githubusercontent.com/65957201/108376466-f02a5180-71fa-11eb-931b-cabac98f59f4.png)

**Comment by tsbkelly** [comment]
Hi,

Can you try using a MIDI monitor (like this one - https://www.snoize.com/MIDIMonitor/) to see the output from the Streamdeck virtual MIDI port directly, please? Could you also send me your Logic file so I can see what you've done in the Environment?

Thanks

**Comment by DrIgnatiusCole** [comment]
Absolutely! Thanks for the quick response. Expect it in a few hours.

**Comment by DrIgnatiusCole** [comment]
Hi there,

I already had midi monitor (been out on that boat before) and initially only program change 2 showed up. I fettled and fiddled, and eventually I got program change 1 to work. But program change 0 is still not showing up either in Logic or the midi monitor….

…except I double and checked just now and it did, after I changed the number and then changed it back.

I am not sure what is going on - that you have to press return - which doesn’t change anything in the UI or click outside the Midi program change number box.

There must be some kind of initalization thing that has to happen after you enter your desired information in the field. It’s not a problem if we know how to resolve it.

So you can mark this as resolved I guess.

**Comment by tsbkelly** [comment]
I think that might be fixed in the next update - I've changed the behaviour so the PI automatically the stored value when the textbox is changed. I'm hoping to get a new version out in the next couple of weeks.

Thanks

**Comment by DrIgnatiusCole** [comment]
Cool. So glad I found this. Seriously - bravo on what ought to have come with SD in the first place.

**Comment by tsbkelly** [comment]
No worries! Thanks - yeah, weird that Elgato didn't code one in to start with

**Comment by DrIgnatiusCole** [comment]
Hi,

I am still having problems with this issue:




You can see that midi monitor is registering the midi message from stream deck as a note off c-2, rather than a program change, yet the button next to it which is set up to be program change 1, is sending correctly.

Initially the button was set up and I tried reinstantiating it in the stream deck app which is why it showing the default icon. So fixing it that way didn’t;t work either.

It’s not that it is midi program change=0, because I have it set up and working in another bank.

**Comment by tsbkelly** [comment]
Hi,

Your message didn't include a screenshot - could you send again, please? Could you also turn on the debug option in the settings, try creating the problem button again, and then send me the log files in ~/Library/Logs/StreamDeck

Thanks
